Add timeout for TLS handshakes
eclipse-zenoh/zenoh pull request #1514
Opened 2024-10-04 16:05 UTC by fuzzypixelz

After establishing a TCP connections, the TLS link waits for the TLS handshake to complete in `rustls`. If the TLS handshake never takes place, then the TLS link waits _forever_ and no one else can establish a Zenoh session. It is thus possible to block a router with a TLS on `tls/127.0.0.1:7447` listener from servicing any incoming connections with the following:

```rust
fn main() {
    let _stream = TcpStream::connect("127.0.0.1:7447")?;
    thread::park();
}
```

2024-10-05 09:44 UTC, gabrik requested changes

2024-10-05 09:44 UTC, gabrik commented on io/zenoh-links/zenoh-link-tls/src/unicast.rs
> +                            dbg!(Duration::from_millis(*TLS_HANDSHAKE_TIMEOUT_MS)),
remove the `dbg!`

2024-10-05 09:44 UTC, gabrik commented on io/zenoh-links/zenoh-link-tls/src/lib.rs
> +    static ref TLS_HANDSHAKE_TIMEOUT_MS: u64 = 10_000;
should this be configurable?

2024-10-05 09:46 UTC, gabrik commented
I'm thinking if we should also spawn a task on accept, or have a task pool where we sent the accepted socket before waiting for the the TLS handshake to complete.

2024-10-07 07:17 UTC, fuzzypixelz commented
> I'm thinking if we should also spawn a task on accept, or have a task pool where we sent the accepted socket before waiting for the the TLS handshake to complete.

Yes, this is effectively what the [`tcp-listener`](https://docs.rs/tls-listener/latest/tls_listener/) crate does.

We should be careful as `tcp-listener` has had [`CVE-2024-28854`](https://www.cve.org/CVERecord?id=CVE-2024-28854) where it was vulnerable to a slow-loris DoS attack.

2024-10-07 08:10 UTC, gabrik commented
I think we need to add a key in order to make the timeout configurable, see: https://github.com/eclipse-zenoh/zenoh/blob/tls-handshake-timeout/io/zenoh-links/zenoh-link-tls/src/lib.rs#L88

2024-10-07 09:14 UTC, fuzzypixelz commented
> I think we need to add a key in order to make the timeout configurable, see: https://github.com/eclipse-zenoh/zenoh/blob/tls-handshake-timeout/io/zenoh-links/zenoh-link-tls/src/lib.rs#L88

Those keys are for runtime configuration, but `TLS_HANDSHAKE_TIMEOUT_MS` is a compile-time constant. Maybe we should make this runtime-configurable.

2024-10-07 10:03 UTC, gabrik commented
> Those keys are for runtime configuration, but `TLS_HANDSHAKE_TIMEOUT_MS` is a compile-time constant. Maybe we should make this runtime-configurable.

I think it must be runtime-configurable as the timeout depends the deployment

2024-10-07 11:59 UTC, gabrik approved these changes

2024-10-07 12:13 UTC, oteffahi approved these changes

2024-10-07 12:14 UTC, merged