Nolocal close
eclipse-zenoh/zenoh pull request #1632
Opened 2024-12-05 13:06 UTC by yellowhatter

Implement close in the way it can be safely waited and awaited in atexit

2024-12-10 06:15 UTC, evshary commented
It still failed when I tested with the following code

```rust
use std::sync::OnceLock;
use zenoh::{Config, Session, Wait};
static SESSION: OnceLock<Session> = OnceLock::new();

fn main() {
    let s = SESSION.get_or_init(|| zenoh::open(Config::default()).wait().unwrap());
    println!("> zid: {}", s.zid());
    unsafe { libc::atexit(close_session) };
}

extern "C" fn close_session() {
    SESSION.get().unwrap().close().wait().unwrap();
}
```

2024-12-23 07:51 UTC, YuanYuYuan commented
Hi @yellowhatter, the RP seems not to work with the following code.
```rust
use std::sync::OnceLock;
use zenoh::{Config, Session, Wait};
static SESSION: OnceLock<Session> = OnceLock::new();

fn main() {
    let s = SESSION.get_or_init(|| zenoh::open(Config::default()).wait().unwrap());
    println!("> zid: {}", s.zid());
    unsafe { libc::atexit(close_session) };
}

extern "C" fn close_session() {
    SESSION.get().unwrap().close().in_background().wait();
}
```

Can you briefly state what this PR aims to resolve?

2024-12-23 09:28 UTC, yellowhatter commented
> Hi @yellowhatter, the RP seems not to work with the following code.
> 
> ```rust
> use std::sync::OnceLock;
> use zenoh::{Config, Session, Wait};
> static SESSION: OnceLock<Session> = OnceLock::new();
> 
> fn main() {
>     let s = SESSION.get_or_init(|| zenoh::open(Config::default()).wait().unwrap());
>     println!("> zid: {}", s.zid());
>     unsafe { libc::atexit(close_session) };
> }
> 
> extern "C" fn close_session() {
>     SESSION.get().unwrap().close().in_background().wait();
> }
> ```
> 
> Can you briefly state what this PR aims to resolve?

This PR just allows you to `wait()` for Session close to complete inside `atexit` handler. However, it still doesn't allow `close()` to be called from `atexit` because after some discussion with Luca we decided not to spend time on this functionality and put it to the very long-term backlog.

> Regarding your nolocal close idea, how do you avoid the underlying Zenoh runtime spawning a new task on a new thread for termination and then `block_in_place` on it? This may still happen.

I didn't get the problem here, can you please explain it?

2025-03-10 13:06 UTC, yellowhatter commented
I've got to add tests and close() call possibility inside atexit()

2025-03-10 14:26 UTC, YuanYuYuan commented
> I've got to add tests and close() call possibility inside atexit()

Nice!

2025-03-11 14:31 UTC, yellowhatter commented
UPD: now the following code works:
```Rust
//
// Copyright (c) 2023 ZettaScale Technology
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License 2.0 which is available at
// http://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
// which is available at https://www.apache.org/licenses/LICENSE-2.0.
//
// SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
//
// Contributors:
//   ZettaScale Zenoh Team, <zenoh@zettascale.tech>
//
use clap::Parser;
use std::sync::OnceLock;
use zenoh::Wait;
use zenoh::{Config, Session};
use zenoh_examples::CommonArgs;

static SESSION: OnceLock<Session> = OnceLock::new();

#[tokio::main]
async fn main() {
    // initiate logging
    zenoh::init_log_from_env_or("error");

    let config = parse_args();

    println!("Opening session...");
    let session = SESSION.get_or_init(move || zenoh::open(config).wait().unwrap());
    println!("Opened zid: {}", session.zid());

    unsafe { libc::atexit(close_session_in_atexit) };
}

extern "C" fn close_session_in_atexit() {
    let session = SESSION.get().unwrap();
    let zid = session.zid();
    println!("Closing session...");
    let _ = session.close().wait().unwrap();
    println!("Closed zid: {}", zid);
}

#[derive(Parser, Clone, Debug)]
struct Args {
    #[command(flatten)]
    common: CommonArgs,
}

fn parse_args() -> Config {
    let args = Args::parse();
    args.common.into()
}
```

2025-03-18 10:08 UTC, yellowhatter commented
Added tests for atexit-safe `close`

2025-03-19 07:46 UTC, YuanYuYuan commented
I ran `cargo nextest run -F internal_config atexit` under the toolchain 1.85.0 and it failed with the log below. 

```console
 Nextest run ID 682535f6-b3ce-4b58-8407-169f1e7f2196 with nextest profile: default
    Starting 1 test across 22 binaries (102 tests skipped)
  TRY 1 FAIL [   1.474s] zenoh::atexit session_close_in_atexit
──── TRY 1 STDOUT:       zenoh::atexit session_close_in_atexit

running 1 test
test session_close_in_atexit ... FAILED

failures:

failures:
    session_close_in_atexit

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 2 filtered out; finished in 1.47s

──── TRY 1 STDERR:       zenoh::atexit session_close_in_atexit

thread 'session_close_in_atexit' panicked at zenoh/tests/atexit.rs:79:5:
Inner test failed
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

   RETRY 2/3 [         ] zenoh::atexit session_close_in_atexit
  TRY 2 FAIL [   0.769s] zenoh::atexit session_close_in_atexit
──── TRY 2 STDOUT:       zenoh::atexit session_close_in_atexit

running 1 test
test session_close_in_atexit ... FAILED

failures:

failures:
    session_close_in_atexit

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 2 filtered out; finished in 0.76s

──── TRY 2 STDERR:       zenoh::atexit session_close_in_atexit

thread 'session_close_in_atexit' panicked at zenoh/tests/atexit.rs:79:5:
Inner test failed
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

   RETRY 3/3 [         ] zenoh::atexit session_close_in_atexit
  TRY 3 FAIL [   0.640s] zenoh::atexit session_close_in_atexit
──── TRY 3 STDOUT:       zenoh::atexit session_close_in_atexit

running 1 test
test session_close_in_atexit ... FAILED

failures:

failures:
    session_close_in_atexit

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 2 filtered out; finished in 0.63s

──── TRY 3 STDERR:       zenoh::atexit session_close_in_atexit

thread 'session_close_in_atexit' panicked at zenoh/tests/atexit.rs:79:5:
Inner test failed
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

  Cancelling due to test failure
────────────
     Summary [   2.887s] 1 test run: 0 passed, 1 failed, 102 skipped
  TRY 3 FAIL [   0.640s] zenoh::atexit session_close_in_atexit
error: test run failed
```

Maybe different optimization cause the panic since 1.75.0 works fine.

2025-03-19 07:56 UTC, YuanYuYuan requested changes

2025-03-19 07:56 UTC, YuanYuYuan commented on zenoh/tests/atexit.rs
> +        .set(vec!["tcp/127.0.0.1:19447".parse().unwrap()])
This port appears to be in use in _zenoh/test/shm.rs_.

2025-03-19 07:56 UTC, YuanYuYuan commented on Cargo.toml
> +async-channel = "2.3.1"
Can we use tokio's channel rather than import a new dependence? IIRC, it's independent of runtime.
https://users.rust-lang.org/t/channels-across-runtimes/100055/5

2025-03-19 08:04 UTC, yellowhatter commented
> cargo nextest run -F internal_config atexit

Good catch!
I've tested and I see that since 1.85 std::thread::spawn also uses TLS.... need to bypass it

2025-03-19 10:12 UTC, yellowhatter commented
Regarding 1.85: [there is a regression in std](https://github.com/rust-lang/rust/issues/138696)

2025-03-20 11:22 UTC, yellowhatter commented on Cargo.toml
> +async-channel = "2.3.1"
removed!

2025-03-20 11:23 UTC, yellowhatter commented on zenoh/tests/atexit.rs
> +        .set(vec!["tcp/127.0.0.1:19447".parse().unwrap()])
fixed!

2025-03-20 11:23 UTC, yellowhatter commented on zenoh/tests/atexit.rs
> +// Copyright (c) 2023 ZettaScale Technology
fixed

2025-03-21 10:31 UTC, YuanYuYuan commented on zenoh/tests/session.rs
> +    tokio::task::block_in_place(move || {
Why do we need to add `block_in_place` here?

2025-03-21 11:20 UTC, yellowhatter commented on zenoh/tests/session.rs
> +    tokio::task::block_in_place(move || {
As long as I use tokio's channel (inside `close_task_X.wait()`), it checks and panics if I try to `wait()` within the async context :)

2025-03-21 11:28 UTC, yellowhatter commented
> @yellowhatter I saw you disabled the test after 1.85. But do we need to disable the function as well? Just in case a user encounters this error using a toolchain newer than 1.75. Others LGTM.

Well, the function is already "disabled" as the close will panic. I just don't want to pull additional dependencies (rust_version) to the binary.

2025-03-21 17:01 UTC, yellowhatter commented on zenoh/src/api/builders/close.rs
> +                std::thread::spawn(evaluate)
Agree, I added a panic here if close() happens on nolocal context without Rust support

2025-03-24 09:03 UTC, YuanYuYuan commented on zenoh/src/api/builders/close.rs
> +                std::thread::spawn(evaluate)
Reviewed. An elegant solution!

2025-03-24 09:28 UTC, yellowhatter commented on zenoh/src/api/builders/close.rs
> +                std::thread::spawn(evaluate)
Thanks!

2025-03-24 12:42 UTC, merged