Refactor storage manager plugin
eclipse-zenoh/zenoh pull request #378
Opened 2022-11-14 15:33 UTC by sreeja

This PR follows the discussion here: https://github.com/eclipse-zenoh/roadmap/discussions/63

2023-04-12 16:30 UTC, JEnoch requested changes

2023-04-12 16:30 UTC, JEnoch commented on plugins/zenoh-plugin-storage-manager/src/replica/storage.rs
> +                let mut storage = self.storage.lock().await;
Lock could be acquired below, just before `match storage.get(stripped_key, "")...`

2023-04-12 16:30 UTC, JEnoch commented on plugins/zenoh-plugin-storage-manager/src/replica/storage.rs
> +        drop(wildcards);
Useless drop since coming out of scope here

2023-04-12 16:30 UTC, JEnoch commented on plugins/zenoh-plugin-storage-manager/src/replica/storage.rs
> +        drop(tombstones);
Useless drop since coming out of scope here

2023-04-12 16:30 UTC, JEnoch commented on plugins/zenoh-plugin-storage-manager/src/replica/storage.rs
> +                drop(storage);
Couldn't this drop be called earlier, just before `if self.replication.is_some()` ?
This would minimise the lock time.

2023-04-12 16:30 UTC, JEnoch commented on plugins/zenoh-plugin-storage-manager/src/replica/storage.rs
> +        drop(wildcard_updates);
Useless drops as coming out of scope here

2023-04-13 06:53 UTC, sreeja commented on plugins/zenoh-plugin-storage-manager/src/replica/storage.rs
> +pub const GC_PERIOD: Duration = Duration::new(30, 0);
Added a comment as a placeholder for now.

2023-04-14 08:50 UTC, merged