Time interval filtering in PublicationCache query
eclipse-zenoh/zenoh pull request #524
Opened 2023-07-28 19:00 UTC by juanjole

Hello, I added support for time interval filtering in the queries for a PublicationCache storage instance.

2023-07-29 09:12 UTC, Mallets commented
Hello @juanjole , thanks for your contribution! In order to be able to merge the PR we would need you to sign the [Eclipse Contribution Agreement](https://accounts.eclipse.org/user/login?destination=legal/eca/validation/166442).

2023-07-29 12:27 UTC, juanjole commented
@Mallets Done!

2023-07-31 07:00 UTC, Mallets requested changes

2023-07-31 12:08 UTC, Mallets approved these changes

2023-07-31 12:08 UTC, merged