Fix crash in replication logic when removing logs from interval.
eclipse-zenoh/zenoh pull request #933
Opened 2024-04-13 23:21 UTC by pftbest

Fixes #931

2024-04-15 10:36 UTC, J-Loudet requested changes
Hi @pftbest, thank you for your contribution!

I have one minor suggestion to your PR (although the suggestion could have been applied on our code…). I have tested the reported issue and can no longer reproduce it after your changes.

2024-04-15 10:36 UTC, J-Loudet commented on plugins/zenoh-plugin-storage-manager/src/replica/digest.rs
> +                        !element_identical
This could be simplified like so:
```suggestion
                        x.timestamp != entry.timestamp || x.key != entry.key
```

2024-04-15 11:51 UTC, pftbest commented on plugins/zenoh-plugin-storage-manager/src/replica/digest.rs
> +                        !element_identical
Done

2024-04-16 07:15 UTC, fuzzypixelz commented
> clippy segfaulted :/

That's okay, it will be fixed when merging #935.

2024-04-16 07:30 UTC, J-Loudet approved these changes

2024-04-16 10:36 UTC, merged